### ISSUE TITLE
Woocommerce issues

### ISSUE THREAD

**Issue by bboerendans** [alaca/WP-Performance#11]
We have issues on different websites where woocommerce is installed. 
For example, you are not able to do the payment, or even to add a product to cart (if its ajax based).

Is this something we have to exclude manually?

**Comment by alaca** [comment]
Hi, could be a problem with minify or async loading of js files. If you use those options, try to turn them OFF. If that is not the case, please send me the link to your website so I can take a look.

Thanks.

**Comment by alaca** [comment]
This issue is sorted out in version1.1.6
