### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'version' (T_STRING)

### ISSUE THREAD

**Issue by cmhello** [alaca/WP-Performance#17]
PHP 7.2

`PHP Parse error:  syntax error, unexpected 'version' (T_STRING) in /www/wwwroot/www.abc.com/wp-content/cache/wpp-cache/www.abc.com/xxxxxxxxxxx.html/feed/index.html on line 1`

**Comment by alaca** [comment]
What should be on that endpoint, RSS feed? It would be great if you could send me the link to the site.
Thanks

**Comment by cmhello** [comment]
`[04-Oct-2019 12:07:21 UTC] PHP Parse error:  syntax error, unexpected 'version' (T_STRING) in /www/wwwroot/www.wpdaxue.com/wp-content/cache/wpp-cache/www.wpdaxue.com/feed/index.html on line 1`

https://www.wpdaxue.com/wp-content/cache/wpp-cache/www.wpdaxue.com/feed/index.html

**Comment by alaca** [comment]
Exclude www.wpdaxue.com/feed from cache, JS and CSS optimization

**Comment by cmhello** [comment]
OK. I will do that.
Thanks!
